# Generated by Django 3.2.20 on 2023-07-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_specials'),
    ]

    operations = [
        migrations.AddField(
            model_name='specials',
            name='today',
            field=models.BooleanField(default=True),
        ),
    ]
