# Generated by Django 3.2.20 on 2023-07-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_auto_20230721_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specials',
            name='today',
            field=models.CharField(max_length=5),
        ),
    ]
